[phases.setup]
nixpkgs = ["python311", "bash", "nodejs_18"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[phases.start]
cmd = "python3 -m uvicorn api_qa:app --host 0.0.0.0 --port $PORT"
