name: Daily UCL Data Update

on:
  schedule:
    - cron: '0 2 * * *'   # 每天 UTC 02:00（北京时间 10:00）
  workflow_dispatch:      # 手动触发

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # 允许 push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install scrapy

      - name: Install Node deps
        run: npm ci

      - name: Run daily update
        run: |
          chmod +x scripts/daily_update.sh
          ./scripts/daily_update.sh

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/*.json data/supplement/ data/ucl_*.jsonl
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "chore: auto update UCL data $(date '+%Y-%m-%d')"
            git push
          )